name: Build APK and Release

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out your code

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use JDK 11 (or whatever version your project requires

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Build APK
        run: ./gradlew assembleRelease  # Build APK file

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3  # Update to v3 (latest version)
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk  # Path to the APK file

  release:
    runs-on: ubuntu-latest
    needs: build  # Depends on the 'build' job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: gh actions/create-release@v1
        with:
          tag_name: v1.0.0  # Tag for the release
          release_name: "Release v1.0.0"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to release
        uses: gh actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk  # Path to the APK file
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive